CREATE TABLE `banner_source` (
	`source_id` INT(11) NOT NULL AUTO_INCREMENT,
	`banner_id` INT(11) NULL DEFAULT NULL,
	`source_name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`source_native_id` VARCHAR(128) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`source_url` TEXT NULL,
	`created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`created_by` INT(11) NULL DEFAULT NULL,
	`updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`updated_by` INT(11) NULL DEFAULT NULL,
	`deleted_date` TIMESTAMP NULL DEFAULT NULL,
	`deleted_by` INT(11) NULL DEFAULT NULL,
	`version` INT(11) NOT NULL DEFAULT '1',
	`validated_date` TIMESTAMP NULL DEFAULT NULL,
	`validated_by` INT(11) NULL DEFAULT NULL,
	`source_banner_name` VARCHAR(128) NULL DEFAULT NULL,
	`source_created_date` TIMESTAMP NULL DEFAULT NULL,
	`source_edited_date` TIMESTAMP NULL DEFAULT NULL,
	`source_deleted_date` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`source_id`),
	UNIQUE INDEX `Index 3` (`source_name`, `source_native_id`),
	INDEX `FK_banner_source_banner` (`banner_id`),
	CONSTRAINT `FK_banner_source_banner` FOREIGN KEY (`banner_id`) REFERENCES `banner` (`banner_id`) ON DELETE SET NULL
)