CREATE TABLE `user_boundary` (
	`user_boundary_id` INT(11) NOT NULL AUTO_INCREMENT,
	`boundary` MULTIPOLYGON NULL DEFAULT NULL,
	`geojson` JSON NULL DEFAULT NULL,
	`created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`created_by` INT(11) NULL DEFAULT NULL,
	`updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`updated_by` INT(11) NULL DEFAULT NULL,
	`deleted_date` TIMESTAMP NULL DEFAULT NULL,
	`deleted_by` INT(11) NULL DEFAULT NULL,
	`version` INT(11) NOT NULL DEFAULT '1',
	PRIMARY KEY (`user_boundary_id`)
)