package com.mtn.constant;

/**
 * Created by Allen on 5/6/2017.
 */
public enum PermissionType {
    GROUPS_CREATE,
    GROUPS_DELETE,
    GROUPS_READ,
    GROUPS_UPDATE,
    PERMISSIONS_READ,
    PERMISSIONS_UPDATE,
    ROLES_CREATE,
    ROLES_DELETE,
    ROLES_READ,
    ROLES_UPDATE,
    SEARCH_READ,
    SHOPPING_CENTER_SURVEYS_CREATE,
    SHOPPING_CENTER_SURVEYS_DELETE,
    SHOPPING_CENTER_SURVEYS_READ,
    SHOPPING_CENTER_SURVEYS_UPDATE,
    SHOPPING_CENTERS_CREATE,
    SHOPPING_CENTERS_DELETE,
    SHOPPING_CENTERS_READ,
    SHOPPING_CENTERS_UPDATE,
    SITES_CREATE,
    SITES_DELETE,
    SITES_READ,
    SITES_UPDATE,
    STORES_CREATE,
    STORES_DELETE,
    STORES_READ,
    STORES_UPDATE,
    USERS_CREATE,
    USERS_DELETE,
    USERS_READ,
    USERS_UPDATE
}
